### ISSUE TITLE
Issues with step3 of resistance make

### ISSUE THREAD

**Issue by nenadmacesic** [c2-d2/rase-db-skeleton#9]
Hi,
I have tried to install the database as instructed but keep getting this error message in step 3 of the make process in the resistance step.
`make[3]: Entering directory '/home/nmacesic/nanopore_realtime/rase_klebs_db/resistance'
rase_db_assign_re_cat.py --in-tsv _isolates.tsv --taxid-col 0 --breakpoint  --mic-col 2 --antibiotic ant1 > _res_cat.ant1.tsv
usage: rase_db_assign_re_cat.py [-h] -i str -t int -m str -b float [-a str]
rase_db_assign_re_cat.py: error: argument -b/--breakpoint: expected one argument
make[3]: *** [Makefile:35: step3] Error 2
make[3]: Leaving directory '/home/nmacesic/nanopore_realtime/rase_klebs_db/resistance'
make[2]: *** [Makefile:21: .res_cat.complete] Error 2
make[2]: Leaving directory '/home/nmacesic/nanopore_realtime/rase_klebs_db/resistance'
make[1]: *** [Makefile:30: resistance] Error 2
make[1]: Leaving directory '/home/nmacesic/nanopore_realtime/rase_klebs_db'
make: *** [Makefile:14: all] Error 2`

I have altered the config file and created a res_cat.tsv file, all as suggested and using the SPARC and GISP databases as a guide. Any ideas/suggestions are much appreciated.

**Comment by karel-brinda** [comment]
The problem seems to be some missing values – the breakpoints are not being passed by GNU Make. You probably need to update your `conf.mk`.

More specifically, when Make is called,
you should see something like 
```
rase_db_assign_re_cat.py --in-tsv _isolates.tsv --taxid-col 0 --breakpoint 0.5 --mic-col 2 --antibiotic some_real_abbreviation
```
instead of
```
rase_db_assign_re_cat.py --in-tsv _isolates.tsv --taxid-col 0 --breakpoint --mic-col 2 --antibiotic ant1
```
